### PR TITLE
added hard question in DSU Leetcode

### PR DESCRIPTION
**Pull request by diva-21**
Hello there,
I have added DSU hard imp question i.e no.of islands 2
Kindly review it

### CODE REVIEW

**Comment by nikoo28** [comment]
your code does not compile...can you have a look at it?

**Comment by diva-21** [comment]
> your code does not compile...can you have a look at it?

sure , give me some time

**Comment by diva-21** [comment]
I have modified the file, added main and other changes
@nikoo28

**Comment by nikoo28** [comment]
Can you remove the main method and put some test cases instead. The code gets easy to maintain.
If you are new to writing test cases, let me know...I will take care of that part.

Once again...thanks for your contribution.

**Comment by diva-21** [comment]
Hey @nikoo28 , can you once give me some sample of writing testcases, i know to write but not in your way.
If not , you can directly merge it

**Comment by SairajSonawane** [comment]
can i also contribute??

**Comment by diva-21** [comment]
> can i also contribute??

if you can add the test cases, it would be good

**Comment by nikoo28** [comment]
So sorry, I have not been able to get on top of this PR…but yes..feel free to add the test cases.Thanks and RegardsNikhil Lohiahttp://www.studyalgorithms.comOn Jan 26, 2023, at 23:39, Divakar ***@***.***> wrote:﻿

can i also contribute??

if you can add the test cases, it would be good

**Comment by nikoo28** [comment]
@SairajSonawane , nothing wrong...I was on my mobile and I think that is how the email rendered the reply. Sorry for the confusion.

Yes, you can go ahead and try adding the test cases, I will review them for sure. :)

**Comment by SairajSonawane** [comment]
ok thanks and sorry for late reply

**Pull request closed without merging**
