### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by GouthamGuna**
The given code is an implementation of the Sherlock and Cost problem.

### CODE REVIEW

**Comment by GouthamGuna** [comment]
Hi @nikoo28 

Please review the code, and if it meets your approval, proceed to approve it. Otherwise, I would appreciate suggestions for improvement.

**Comment by nikoo28** [comment]
Please add test cases as well, and add a link to the problem statement too

**Comment by GouthamGuna** [comment]
Hello, @nikoo28

Please check the code, and I will add the test case.

**Review by nikoo28 — APPROVED** [review]
thanks for your contribution!!

**Pull request merged**
